batch_size: 512
epochs: 300
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 64
  base_model: "encoder"
  imsize: 32

dataset:
  parent: "Office31"
  dset_taples: [['dslr', [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]], ['webcam', [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]]]
  jigsaw: True
  save_name: "encoder_jigsaw_grid_3"
  grid: 3
loss:
  temperature: 0.5
  use_cosine_similarity: True
